expected = 11.85255;
actual = COPFinSet([0.75,1.6,0.85,11.2])
assert (...
    actual == expected, ...
    'COPFinSet() \n actual = %d \n expected = %d ', actual, expected ...
);

disp('If no error, all clean!');
