%% Import data from text file.
% Script for importing data from the following text file:
%
%    C:\Users\scorpii\Documents\Space\Rocketry\Performance\rocketry-performance\data\aurelius_rocksim_simulation.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2016/01/19 18:57:29

%% Initialize variables.
%filename = 'aurelius_rocksim_simulation.csv';
filename = 'aurelius_rocksim_worst_1243.csv';
delimiter = ',';
startRow = 2;

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
%   column11: double (%f)
%	column12: double (%f)
%   column13: double (%f)
%	column14: double (%f)
%   column15: double (%f)
%	column16: double (%f)
%   column17: double (%f)
%	column18: double (%f)
%   column19: double (%f)
%	column20: double (%f)
%   column21: double (%f)
%	column22: double (%f)
%   column23: double (%f)
%	column24: double (%f)
%   column25: double (%f)
%	column26: double (%f)
%   column27: double (%f)
%	column28: double (%f)
%   column29: double (%f)
%	column30: double (%f)
%   column31: double (%f)
%	column32: double (%f)
%   column33: double (%f)
%	column34: double (%f)
%   column35: double (%f)
%	column36: double (%f)
%   column37: double (%f)
%	column38: double (%f)
%   column39: double (%f)
%	column40: double (%f)
%   column41: double (%f)
%	column42: double (%f)
%   column43: double (%f)
%	column44: double (%f)
%   column45: double (%f)
%	column46: double (%f)
%   column47: double (%f)
%	column48: double (%f)
%   column49: double (%f)
%	column50: double (%f)
%   column51: double (%f)
%	column52: double (%f)
%   column53: double (%f)
%	column54: double (%f)
%   column55: double (%f)
%	column56: double (%f)
%   column57: double (%f)
%	column58: double (%f)
%   column59: double (%f)
%	column60: double (%f)
%   column61: double (%f)
%	column62: double (%f)
%   column63: double (%f)
%	column64: double (%f)
%   column65: double (%f)
%	column66: double (%f)
%   column67: double (%f)
%	column68: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'HeaderLines' ,startRow-1, 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
Rocksim_Time = dataArray{:, 1};
Rocksim_ThrustN = dataArray{:, 2};
Rocksim_xThrustN = dataArray{:, 3};
Rocksim_yThrustN = dataArray{:, 4};
Rocksim_AccelerationFeetsecsec = dataArray{:, 5};
Rocksim_xAccelerationFeetsecsec = dataArray{:, 6};
Rocksim_yAccelerationFeetsecsec = dataArray{:, 7};
Rocksim_AccelerationTotalFeetsecsec = dataArray{:, 8};
Rocksim_xAccelerationTotalFeetsecsec = dataArray{:, 9};
Rocksim_yAccelerationTotalFeetsecsec = dataArray{:, 10};
Rocksim_VelocityFeetSec = dataArray{:, 11};
Rocksim_xVelocityFeetSec = dataArray{:, 12};
Rocksim_yVelocityFeetSec = dataArray{:, 13};
Rocksim_Machnumber = dataArray{:, 14};
Rocksim_AltitudeFeet = dataArray{:, 15};
RockSim_AltitudeMeters = Rocksim_AltitudeFeet * 3.281;
Rocksim_RangeFeet = dataArray{:, 16};
Rocksim_Cd = dataArray{:, 17};
Rocksim_DragforceN = dataArray{:, 18};
Rocksim_xDragforceN = dataArray{:, 19};
Rocksim_yDragforceN = dataArray{:, 20};
Rocksim_LongitudinalmomentofinertiaOuncesInches2 = dataArray{:, 21};
Rocksim_RadialmomentofinertiaOuncesInches2 = dataArray{:, 22};
Rocksim_FlightangleDeg = dataArray{:, 23};
Rocksim_GammaVelocitytangentangleDeg = dataArray{:, 24};
Rocksim_WindangleofattackDeg = dataArray{:, 25};
Rocksim_CGInches = dataArray{:, 26};
Rocksim_MassOunces = dataArray{:, 27};
Rocksim_CPInches = dataArray{:, 28};
Rocksim_CNanormalforcecoefficient = dataArray{:, 29};
Rocksim_StaticstabilitymarginCalibers = dataArray{:, 30};
Rocksim_AngularaccelerationRadss = dataArray{:, 31};
Rocksim_TorqueNm = dataArray{:, 32};
Rocksim_Pitchraterads = dataArray{:, 33};
Rocksim_PitchforceN = dataArray{:, 34};
Rocksim_xWindvelocityMilesHour = dataArray{:, 35};
Rocksim_CrosswinddragN = dataArray{:, 36};
Rocksim_CrosswindliftN = dataArray{:, 37};
Rocksim_XWindinducedaccelerationFeetsecsec = dataArray{:, 38};
Rocksim_YWindinducedliftFeetsecsec = dataArray{:, 39};
Rocksim_XWinddriftvelocityFeetSec = dataArray{:, 40};
Rocksim_YWinddriftvelocityFeetSec = dataArray{:, 41};
Rocksim_ThermalrisevelocityMilesHour = dataArray{:, 42};
Rocksim_GravityFeetsecsec = dataArray{:, 43};
Rocksim_PressureKPa = dataArray{:, 44};
Rocksim_TemperatureDegreesFahrenheit = dataArray{:, 45};
Rocksim_Densitykgm3 = dataArray{:, 46};
Rocksim_Viscosity = dataArray{:, 47};
Rocksim_Kinematicviscosity = dataArray{:, 48};
Rocksim_SoundvelocityFeetSec = dataArray{:, 49};
Rocksim_Correctivemomentcoefficient = dataArray{:, 50};
Rocksim_Dampingmomentcoefficient = dataArray{:, 51};
Rocksim_NatFreqatzerorollraterads = dataArray{:, 52};
Rocksim_DampingRatio = dataArray{:, 53};
Rocksim_PrecFreqrads = dataArray{:, 54};
Rocksim_NatCoupledFrequencyrads = dataArray{:, 55};
Rocksim_CoupledDampingRatio = dataArray{:, 56};
Rocksim_Booster2VelocityFeetSec = dataArray{:, 57};
Rocksim_Booster2xVelocityFeetSec = dataArray{:, 58};
Rocksim_Booster2yVelocityFeetSec = dataArray{:, 59};
Rocksim_Booster2rangeFeet = dataArray{:, 60};
Rocksim_Booster2altitudeFeet = dataArray{:, 61};
Rocksim_Booster2flightangleDeg = dataArray{:, 62};
Rocksim_Booster1VelocityFeetSec = dataArray{:, 63};
Rocksim_Booster1xVelocityFeetSec = dataArray{:, 64};
Rocksim_Booster1yVelocityFeetSec = dataArray{:, 65};
Rocksim_Booster1rangeFeet = dataArray{:, 66};
Rocksim_Booster1altitudeFeet = dataArray{:, 67};
Rocksim_Booster1flightangle = dataArray{:, 68};

%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans;

%% Print apogee data to console
fprintf( 'Maximum RockSim altitude:      %d m, %d ft \r',...
    max(RockSim_AltitudeMeters),...
    max(Rocksim_AltitudeFeet)...
);

fprintf( 'Maximum RockSim Velocity:      %d m/s, %d ft/s \r', ...
    max(Rocksim_VelocityFeetSec), ...
    max(Rocksim_VelocityFeetSec) / 3.28 ...
);

fprintf( 'Maximum RockSim acceleration:  %d m/s^2, %d ft/s^2 %d g \r',...
    max(Rocksim_AccelerationTotalFeetsecsec),...
    max(Rocksim_AccelerationTotalFeetsecsec)/3.28, ...
    max(Rocksim_AccelerationTotalFeetsecsec)/32.2 ...
);

fprintf( 'Maximum RockSim drag force:    %d m/s \r', ...
    max(Rocksim_DragforceN)...
);

indexguide = dsearchn(RockSim_AltitudeMeters,launch_guide_length);
Rocksim_guide_velocity = Rocksim_yVelocityFeetSec(indexguide) / 3.28;

fprintf( 'Velocity leaving launch guide: %d m/s \r', ...
    Rocksim_guide_velocity...
);
