%% Import data from text file.
% Script for importing data from the following text file:
%
%    C:\Users\scorpii\Documents\Space\Rocketry\Performance\rocketry-performance\data\Simulations\arcturus_openrocket_greenriver.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2016/03/14 14:06:42

%% Initialize variables.
filename = 'C:\Users\scorpii\Documents\Space\Rocketry\Performance\rocketry-performance\data\Simulations\arcturus_openrocket_greenriver.csv';
delimiter = ',';
startRow = 7;

% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%s%f%s%f%f%f%f%f%f%f%f%f%s%s%s%s%s%s%s%s%f%f%f%f%f%s%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'EmptyValue' ,0.0,'HeaderLines' ,startRow-1, 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
openrocket_VarName1 = dataArray{:, 1};
openrocket_Altitudem = dataArray{:, 2};
openrocket_Verticalvelocityms = dataArray{:, 3};
openrocket_Verticalaccelerationms = dataArray{:, 4};
openrocket_Totalvelocityms = dataArray{:, 5};
openrocket_Totalaccelerationms = dataArray{:, 6};
openrocket_PositionEastoflaunchm = dataArray{:, 7};
openrocket_PositionNorthoflaunchm = dataArray{:, 8};
openrocket_Lateraldistancem = dataArray{:, 9};
openrocket_Lateraldirection = dataArray{:, 10};
openrocket_Lateralvelocityms = dataArray{:, 11};
openrocket_Lateralaccelerationms = dataArray{:, 12};
openrocket_Latitude = dataArray{:, 13};
openrocket_Longitude = dataArray{:, 14};
openrocket_Gravitationalaccelerationms = dataArray{:, 15};
openrocket_Angleofattack = dataArray{:, 16};
openrocket_Rollrates = dataArray{:, 17};
openrocket_Pitchrates = dataArray{:, 18};
openrocket_Yawrates = dataArray{:, 19};
openrocket_Massg = dataArray{:, 20};
openrocket_Propellantmassg = dataArray{:, 21};
openrocket_Longitudinalmomentofinertiakgm = dataArray{:, 22};
openrocket_Rotationalmomentofinertiakgm = dataArray{:, 23};
openrocket_CPlocationcm = dataArray{:, 24};
openrocket_CGlocationcm = dataArray{:, 25};
openrocket_Stabilitymargincalibers = dataArray{:, 26};
openrocket_Machnumber = dataArray{:, 27};
openrocket_Reynoldsnumber = dataArray{:, 28};
openrocket_ThrustN = dataArray{:, 29};
openrocket_DragforceN = dataArray{:, 30};
openrocket_Dragcoefficient = dataArray{:, 31};
openrocket_Axialdragcoefficient = dataArray{:, 32};
openrocket_Frictiondragcoefficient = dataArray{:, 33};
openrocket_Pressuredragcoefficient = dataArray{:, 34};
openrocket_Basedragcoefficient = dataArray{:, 35};
openrocket_Normalforcecoefficient = dataArray{:, 36};
openrocket_Pitchmomentcoefficient = dataArray{:, 37};
openrocket_Yawmomentcoefficient = dataArray{:, 38};
openrocket_Sideforcecoefficient = dataArray{:, 39};
openrocket_Rollmomentcoefficient = dataArray{:, 40};
openrocket_Rollforcingcoefficient = dataArray{:, 41};
openrocket_Rolldampingcoefficient = dataArray{:, 42};
openrocket_Pitchdampingcoefficient = dataArray{:, 43};
openrocket_Coriolisaccelerationms = dataArray{:, 44};
openrocket_Referencelengthcm = dataArray{:, 45};
openrocket_Referenceareacm = dataArray{:, 46};
openrocket_Verticalorientationzenith = dataArray{:, 47};
openrocket_Lateralorientationazimuth = dataArray{:, 48};
openrocket_Windvelocityms = dataArray{:, 49};
openrocket_AirtemperatureC = dataArray{:, 50};
openrocket_Airpressurembar = dataArray{:, 51};
openrocket_Speedofsoundms = dataArray{:, 52};
openrocket_Simulationtimesteps = dataArray{:, 53};
openrocket_Computationtimes = dataArray{:, 54};
openrocket_DynamicPressurembar = dataArray{:, 55};

%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans;

openrocket_summary
