%% Import data from text file.
% Script for importing data from the following text file:
%
%    C:\Users\scorpii\Documents\Space\Rocketry\Performance\rocketry-performance\data\aureliues_rasaero_flight.CSV
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2016/01/23 17:14:12

%% Initialize variables.
filename = 'C:\Users\scorpii\Documents\Space\Rocketry\Performance\rocketry-performance\data\aureliues_rasaero_flight.CSV';
delimiter = ',';
startRow = 2;

%% Format string for each line of text:
%   column1: double (%f)
%	column2: text (%s)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
%   column11: double (%f)
%	column12: double (%f)
%   column13: double (%f)
%	column14: double (%f)
%   column15: double (%f)
%	column16: double (%f)
%   column17: double (%f)
%	column18: double (%f)
%   column19: double (%f)
%	column20: double (%f)
%   column21: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%s%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines' ,startRow-1, 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
rasaero_Timesec = dataArray{:, 1};
rasaero_Stage = dataArray{:, 2};
rasaero_StageTimesec = dataArray{:, 3};
rasaero_Mach = dataArray{:, 4};
rasaero_AngleofAttackdeg = dataArray{:, 5};
rasaero_CD = dataArray{:, 6};
rasaero_CL = dataArray{:, 7};
rasaero_Thrustlb = dataArray{:, 8};
rasaero_Weightlb = dataArray{:, 9};
rasaero_Draglb = dataArray{:, 10};
rasaero_Liftlb = dataArray{:, 11};
rasaero_AccelRftsec2 = dataArray{:, 12};
rasaero_AccelVftsec2 = dataArray{:, 13};
rasaero_AccelHftsec2 = dataArray{:, 14};
rasaero_VelRftsec = dataArray{:, 15};
rasaero_VelVftsec = dataArray{:, 16};
rasaero_VelHftsec = dataArray{:, 17};
rasaero_PitchAttitudedeg = dataArray{:, 18};
rasaero_FlightPathAngledeg = dataArray{:, 19};
rasaero_Altitudeft = dataArray{:, 20};
rasaero_Distanceft = dataArray{:, 21};

%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans;
