%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\scorpii\Documents\Space\Rocketry\Avionics\Arcturus
%    Flight Analysis\Arcturus Flight Data\ArcturusFlightData.xlsx
%    Worksheet: StrattoLogger
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2015/11/24 21:16:09

%% Import the data
[~, ~, raw] = xlsread('ArcturusFlightData.xlsx','StrattoLogger','A2:E602');
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
t_arc_strat            = data(:,1);
baroalt_arc_strat      = data(:,2);
velocity_arc_strat     = data(:,3);
acceleration_arc_strat = data(:,4);
mach_arc_strat         = data(:,5);

%% Clear temporary variables
clearvars data raw R;
