%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\scorpii\Documents\Space\Rocketry\Avionics\Arcturus
%    Flight Analysis\Arcturus Flight Data\ArcturusFlightData.xlsx
%    Worksheet: CA Accelerometer (AA)
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2015/11/24 19:57:14

%% Import the data
[~, ~, raw] = xlsread('C:\Users\scorpii\Documents\Space\Rocketry\Avionics\Arcturus Flight Analysis\Arcturus Flight Data\ArcturusFlightData.xlsx','CA Accelerometer (AA)','A2:E1234');
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
stage_acc_arcturus = data(:,1);
t_acc_arcturus = data(:,2);
x_acc_arcturus = data(:,3);
y_acc_arcturus = data(:,4);
z_acc_arcturus = data(:,5);

%% Clear temporary variables
clearvars data raw R;
