%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\scorpii\Documents\Space\Rocketry\Avionics\Arcturus
%    Flight Analysis\Arcturus Flight Data\ArcturusFlightData.xlsx
%    Worksheet: CA BMP Sensor (PP)
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2015/11/24 20:14:04

%% Import the data
[~, ~, raw] = xlsread('C:\Users\scorpii\Documents\Space\Rocketry\Avionics\Arcturus Flight Analysis\Arcturus Flight Data\ArcturusFlightData.xlsx','CA BMP Sensor (PP)','A2:F2470');

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
%Stage          = data(:,1);
stage_bar_arc       = data(:,2);
t_bar_arc           = data(:,3);
pressure_bar_arc    = data(:,4);
temperature_bar_arc = data(:,5);
altitude_bar_arc    = data(:,6);

xdata = {t_bar_arc, t_bar_arc, t_bar_arc};
ydata = {pressure_bar_arc, temperature_bar_arc, altitude_bar_arc};


%% Clear temporary variables
clearvars data raw;
