<RockSimDocument>
    <FileVersion>4</FileVersion>
    <DesignInformation>
        <RocketDesign>
            <Name>CR-2-4G (Aurelius)</Name>
            <StageCount>1</StageCount>
            <DisplayFlags>7</DisplayFlags>
            <ViewType>0</ViewType>
            <ViewStageCount>3</ViewStageCount>
            <ViewTypeEdit>0</ViewTypeEdit>
            <ViewStageCountEdit>3</ViewStageCountEdit>
            <ZoomFactor>0.0</ZoomFactor>
            <ZoomFactorEdit>0.0</ZoomFactorEdit>
            <ScrollPosX>0</ScrollPosX>
            <ScrollPosY>0</ScrollPosY>
            <ScrollPosXEdit>0</ScrollPosXEdit>
            <ScrollPosYEdit>0</ScrollPosYEdit>
            <ThreeDFlags>0</ThreeDFlags>
            <ThreeDFlagsEdit>0</ThreeDFlagsEdit>
            <LastSerialNumber>21</LastSerialNumber>
            <Stage3Mass>0.0</Stage3Mass>
            <Stage2Mass>0.0</Stage2Mass>
            <Stage1Mass>0.0</Stage1Mass>
            <Stage3CG>1373.940213582288</Stage3CG>
            <Stage2CGAlone>0.0</Stage2CGAlone>
            <Stage1CGAlone>0.0</Stage1CGAlone>
            <Stage321CG>0.0</Stage321CG>
            <Stage32CG>0.0</Stage32CG>
            <CPCalcFlags>1</CPCalcFlags>
            <CPSimFlags>1</CPSimFlags>
            <UseKnownMass>0</UseKnownMass>
            <Stage3Parts>
                <NoseCone>
                    <KnownMass>972.0</KnownMass>
                    <Density>1850.0</Density>
                    <Material>Fiberglass</Material>
                    <Name>Nose cone</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>1</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>499.5153604256657</CalcMass>
                    <CalcCG>371.4103589564791</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>508.0</Len>
                    <FinishCode>1</FinishCode>
                    <SerialNo>1</SerialNo>
                    <ShapeCode>6</ShapeCode>
                    <ConstructionType>1</ConstructionType>
                    <WallThickness>2.0</WallThickness>
                    <ShapeParameter>0.0</ShapeParameter>
                    <AttachedParts>
                        <MassObject>
                            <KnownMass>0.0</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Ballast</Name>
                            <KnownCG>93.00000000000001</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>93.00000000000001</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>30.00000000000001</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>2</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                        <MassObject>
                            <KnownMass>273.0</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Unspecified</Name>
                            <KnownCG>440.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>440.0</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>140.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>3</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                    </AttachedParts>
                    <BaseDia>103.00000000000001</BaseDia>
                    <ShoulderLen>100.0</ShoulderLen>
                    <ShoulderOD>100.0</ShoulderOD>
                </NoseCone>
                <BodyTube>
                    <KnownMass>758.0</KnownMass>
                    <Density>1440.0</Density>
                    <Material>IM7/APC-2</Material>
                    <Name>Upper Body tube</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>1</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>413.25766402381623</CalcMass>
                    <CalcCG>300.0</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>600.0</Len>
                    <FinishCode>1</FinishCode>
                    <SerialNo>4</SerialNo>
                    <OD>103.00000000000001</OD>
                    <ID>100.0</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>100.0</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <MassObject>
                            <KnownMass>772.0</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Recovery Systems Upper</Name>
                            <KnownCG>100.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>100.0</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>400.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>5</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                        <Parachute>
                            <KnownMass>0.0</KnownMass>
                            <Density>0.006700000000000001</Density>
                            <Material>Ripstop nylon</Material>
                            <Name>Main Parachute</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>280.0</Xb>
                            <CalcMass>177.08184395831648</CalcMass>
                            <CalcCG>12.5</CalcCG>
                            <DensityType>1</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>25.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>6</SerialNo>
                            <Dia>1524.0</Dia>
                            <ShroudLineCount>12</ShroudLineCount>
                            <Thickness>0.0</Thickness>
                            <ShroudLineLen>2540.0</ShroudLineLen>
                            <ChuteCount>1</ChuteCount>
                            <ShroudLineMassPerMM>0.0018</ShroudLineMassPerMM>
                            <ShroudLineMaterial>Elastic cord (round 2 mm, 1/16 in)</ShroudLineMaterial>
                            <DragCoefficient>2.2</DragCoefficient>
                        </Parachute>
                    </AttachedParts>
                </BodyTube>
                <BodyTube>
                    <KnownMass>371.0</KnownMass>
                    <Density>1440.0</Density>
                    <Material>IM7/APC-2</Material>
                    <Name>Payload tube</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>1</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>338.1157942981936</CalcMass>
                    <CalcCG>185.0</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>370.0</Len>
                    <FinishCode>1</FinishCode>
                    <SerialNo>7</SerialNo>
                    <OD>103.00000000000001</OD>
                    <ID>99.0</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>99.0</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <Ring>
                            <KnownMass>505.4093730130356</KnownMass>
                            <Density>1440.0</Density>
                            <Material>IM7/APC-2</Material>
                            <Name>Tube coupler+</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>-100.0</Xb>
                            <CalcMass>505.4093730130356</CalcMass>
                            <CalcCG>285.00000000000006</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>570.0000000000001</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>8</SerialNo>
                            <OD>100.0</OD>
                            <ID>96.0</ID>
                            <UsageCode>4</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                    </AttachedParts>
                </BodyTube>
                <BodyTube>
                    <KnownMass>1005.2091181838209</KnownMass>
                    <Density>1440.0</Density>
                    <Material>IM7/APC-2</Material>
                    <Name>Lower Body tube</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>1005.2091181838209</CalcMass>
                    <CalcCG>550.0</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>1100.0</Len>
                    <FinishCode>1</FinishCode>
                    <SerialNo>9</SerialNo>
                    <OD>103.00000000000001</OD>
                    <ID>99.0</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>99.0</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <Parachute>
                            <KnownMass>0.0</KnownMass>
                            <Density>0.006700000000000001</Density>
                            <Material>Ripstop nylon</Material>
                            <Name>Drogue Parachute</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>170.0</Xb>
                            <CalcMass>96.83042382499391</CalcMass>
                            <CalcCG>12.5</CalcCG>
                            <DensityType>1</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>25.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>10</SerialNo>
                            <Dia>914.4</Dia>
                            <ShroudLineCount>4</ShroudLineCount>
                            <Thickness>0.0</Thickness>
                            <ShroudLineLen>1016.0</ShroudLineLen>
                            <ChuteCount>1</ChuteCount>
                            <ShroudLineMassPerMM>0.013</ShroudLineMassPerMM>
                            <ShroudLineMaterial>Tubular nylon (11 mm, 7/16 in)</ShroudLineMaterial>
                            <DragCoefficient>1.5</DragCoefficient>
                        </Parachute>
                        <BodyTube>
                            <KnownMass>257.0028957654346</KnownMass>
                            <Density>1300.0</Density>
                            <Material>Blue tube</Material>
                            <Name>Motor Mount Tube</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>-0.0</Xb>
                            <CalcMass>257.0028957654346</CalcMass>
                            <CalcCG>325.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>650.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>11</SerialNo>
                            <OD>78.7</OD>
                            <ID>76.2</ID>
                            <IsMotorMount>1</IsMotorMount>
                            <MotorDia>76.2</MotorDia>
                            <EngineOverhang>0.0</EngineOverhang>
                            <IsInsideTube>1</IsInsideTube>
                            <AttachedParts>
                                <MassObject>
                                    <KnownMass>154.5</KnownMass>
                                    <Density>0.0</Density>
                                    <Material></Material>
                                    <Name>Motor Retainer</Name>
                                    <KnownCG>-0.0</KnownCG>
                                    <UseKnownCG>1</UseKnownCG>
                                    <Xb>-0.0</Xb>
                                    <CalcMass>0.0</CalcMass>
                                    <CalcCG>0.0</CalcCG>
                                    <DensityType>0</DensityType>
                                    <RadialLoc>0.0</RadialLoc>
                                    <RadialAngle>0.0</RadialAngle>
                                    <LocationMode>0</LocationMode>
                                    <Len>20.0</Len>
                                    <FinishCode>0</FinishCode>
                                    <SerialNo>12</SerialNo>
                                    <TypeCode>0</TypeCode>
                                </MassObject>
                            </AttachedParts>
                        </BodyTube>
                        <Ring>
                            <KnownMass>131.9768504637141</KnownMass>
                            <Density>1800.0</Density>
                            <Material>G10 Fiberglass</Material>
                            <Name>Motor Bulkhead</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>650.0</Xb>
                            <CalcMass>131.9768504637141</CalcMass>
                            <CalcCG>4.762499999999999</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>9.524999999999999</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>13</SerialNo>
                            <OD>99.0</OD>
                            <ID>0.0</ID>
                            <UsageCode>1</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <Ring>
                            <KnownMass>50.0</KnownMass>
                            <Density>1800.0</Density>
                            <Material>G10 Fiberglass</Material>
                            <Name>Motor Centering ring A</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>405.0</Xb>
                            <CalcMass>32.38318623584399</CalcMass>
                            <CalcCG>3.175</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>6.35</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>14</SerialNo>
                            <OD>99.0</OD>
                            <ID>78.7</ID>
                            <UsageCode>0</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <Ring>
                            <KnownMass>50.0</KnownMass>
                            <Density>1800.0</Density>
                            <Material>G10 Fiberglass</Material>
                            <Name>Motor Centering ring B</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>217.5</Xb>
                            <CalcMass>32.38318623584399</CalcMass>
                            <CalcCG>3.175</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>6.35</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>15</SerialNo>
                            <OD>99.0</OD>
                            <ID>78.7</ID>
                            <UsageCode>0</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <Ring>
                            <KnownMass>122.0</KnownMass>
                            <Density>2700.0</Density>
                            <Material>Aluminum</Material>
                            <Name>Motor Centering ring C</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>20.0</Xb>
                            <CalcMass>97.14955870753198</CalcMass>
                            <CalcCG>6.35</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>12.7</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>16</SerialNo>
                            <OD>99.0</OD>
                            <ID>78.7</ID>
                            <UsageCode>0</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <LaunchLug>
                            <KnownMass>9.6</KnownMass>
                            <Density>680.0</Density>
                            <Material>Cardboard</Material>
                            <Name>Launch lug A</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>535.0</Xb>
                            <CalcMass>4.153094381858754</CalcMass>
                            <CalcCG>15.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.7853981633974483</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>30.0</Len>
                            <FinishCode>1</FinishCode>
                            <SerialNo>17</SerialNo>
                            <OD>16.1</OD>
                            <ID>0.0</ID>
                        </LaunchLug>
                        <LaunchLug>
                            <KnownMass>9.6</KnownMass>
                            <Density>680.0</Density>
                            <Material>Cardboard</Material>
                            <Name>Launch lug B</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>985.0000000000001</Xb>
                            <CalcMass>4.153094381858754</CalcMass>
                            <CalcCG>15.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.7853981633974483</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>30.0</Len>
                            <FinishCode>1</FinishCode>
                            <SerialNo>18</SerialNo>
                            <OD>16.1</OD>
                            <ID>0.0</ID>
                        </LaunchLug>
                        <FinSet>
                            <KnownMass>81.0</KnownMass>
                            <Density>1850.0</Density>
                            <Material>Fiberglass</Material>
                            <Name>fin set</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>-0.0</Xb>
                            <CalcMass>609.7072585058751</CalcMass>
                            <CalcCG>167.8673601637784</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>0.0</Len>
                            <FinishCode>1</FinishCode>
                            <SerialNo>19</SerialNo>
                            <FinCount>3</FinCount>
                            <RootChord>280.0</RootChord>
                            <TipChord>100.0</TipChord>
                            <SemiSpan>95.0</SemiSpan>
                            <SweepDistance>160.0</SweepDistance>
                            <Thickness>5.41</Thickness>
                            <ShapeCode>0</ShapeCode>
                            <TipShapeCode>0</TipShapeCode>
                            <TabLength>184.80000000000018</TabLength>
                            <TabDepth>11.649999999999993</TabDepth>
                            <TabOffset>62.00000000000001</TabOffset>
                            <SweepMode>1</SweepMode>
                            <CantAngle>0.0</CantAngle>
                        </FinSet>
                        <MassObject>
                            <KnownMass>654.0</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Finishing Correction</Name>
                            <KnownCG>620.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>620.0</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>470.00000000000006</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>20</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                        <MassObject>
                            <KnownMass>667.0</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Aft Recovery</Name>
                            <KnownCG>120.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>120.0</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>340.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>21</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                    </AttachedParts>
                </BodyTube>
            </Stage3Parts>
            <Stage2Parts/>
            <Stage1Parts/>
        </RocketDesign>
    </DesignInformation>
</RockSimDocument>