function coef_drag_fins_aoa = CoefDragFinsAOA(inputs)

aoa  = inputs(1); % Angle of Attack
A_fp = inputs(2); % Fin Planform Area
A_fe = inputs(3); % Fin Exposed Planform Area
OD_f = inputs(4); % Rocket body diameter at fin mount
k_fb = inputs(5); % Fin-body coefficient
k_bf = inputs(6); % Body-fin coefficient

coef_drag_fins_aoa = ...
    aoa^2 ...
    * ...
    ( ...
    1.2 ...
    * (A_fp * 4) / (pi * OD_f^2) ...
    + ...
    3.12 * (k_fb + k_bf - 1) ...
    * ...
    (A_fe * 4)/(pi * OD_f^2) ...
    );
