function coef_moment_damping = CoefMomentDampingAero(inputs)

aoa                         = inputs(1);
density                     = inputs(2);
velocity                    = inputs(3);
area_ref                    = inputs(4);
cop_nosecone                = inputs(5);
cop_bodytube                = inputs(6);
cop_finset                  = inputs(7);
sd_nosecone                 = inputs(8);
sd_bodytube                 = inputs(9);
sd_finset                   = inputs(10);
rocket_cog                  = inputs(11);

sum_term = 0;

sum_term = sum_term + ...
    sd_nosecone ...
    * ...
    (cop_nosecone - rocket_cog)^2;

sum_term = sum_term + ...
    sd_bodytube ...
    * ...
    (cop_bodytube - rocket_cog)^2;

sum_term = sum_term + ...
    sd_finset ...
    * ...
    (cop_finset - rocket_cog)^2;

%{
coef_moment_damping = ...
    1 / 2 ... 
    * density ...
    * velocity ...
    * area_ref ...
    * sum_term ...
    * aoa;
%}
coef_moment_damping = ...
    1 / 2 ... 
    * 1.29 ...
    * velocity ...
    * area_ref ...
    * sum_term ...
    * aoa;