function coef_fin_body_interference = CoefFinBodyInterference(inputs)

OD         = inputs(1);
fin_height = inputs(2);


coef_fin_body_interference = ...
    1 ...
    + ...
    OD / 2 ...
    / ...
    ( fin_height + OD/2 ) ...
    ;
