function coef_moment_corrective = CoefMomentCorrective(inputs)

density           = inputs(1);
velocity          = inputs(2);
area_ref          = inputs(3);
coef_force_normal = inputs(4);
COP               = inputs(5);
COG               = inputs(6);

coef_moment_corrective = ...
    0.5 ...
    * density ...
    * velocity^2 ...
    * area_ref ...
    * coef_force_normal ...
    * (COP - COG);
