function cop_fin_set = COPFinSet(inputs)

fin_sweep_length    = inputs(1);
fin_root_chord      = inputs(2);
fin_tip_chord       = inputs(3);
d_nose_tip_to_fins  = inputs(4);

cop_fin_set = ...
   d_nose_tip_to_fins ...
   + ...
   ( ...
        fin_sweep_length ...
        * ( fin_root_chord + 2 * fin_tip_chord ) ...
   ) ...
   / ...
   ( 3 * ( fin_root_chord + fin_tip_chord ) ) ...
   ...
   + ...
   ...
   1/6 ...
   * ...
   ( ...
       fin_root_chord + fin_tip_chord ...
       - ...
       ( fin_root_chord * fin_tip_chord ) ...
       / ...
       ( fin_root_chord + fin_tip_chord ) ...
   );