function cop_rocket = COPRocket(inputs)

sd_nosecone         = inputs(1);
sd_bodytube         = inputs(2);
sd_finset           = inputs(3);
sd_lift_correction  = inputs(4);
cop_nose_cone       = inputs(4);
cop_body_tube       = inputs(5);
cop_fin_set         = inputs(7);
cop_rocket_planform = inputs(8);

numerator = ...
    ( sd_nosecone * cop_nose_cone ) ...
    + ...
    ( sd_bodytube * cop_body_tube ) ...
    + ...
    ( sd_finset * cop_fin_set ) ...
    - ...
    ( sd_lift_correction * cop_rocket_planform ) ...
    ;

cop_rocket = ... 
    numerator ...
    / ...
    (sd_nosecone + sd_bodytube + sd_finset + sd_lift_correction);
