function stability_derivative_fin_set = StabilityDerivativeFinSet(inputs)

coef_interference  = inputs(1);
fin_count          = inputs(2);
fin_height         = inputs(3);
center_length      = inputs(4);
fin_tip_length     = inputs(5);
fin_root_length    = inputs(6);
OD                 = inputs(7);

stability_derivative_fin_set = ...
    coef_interference * ...
    ( ...
        4 * fin_count ...
        * (fin_height / OD )^2 ...
    ) ...
    / ...
    ( ...
        1 ...
        + ...
        sqrt( 1 + ( 2*center_length/(fin_tip_length+fin_root_length) )^2 ) ...
    ); 
